[package]
name = "aoc_2024_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy-regex = "0.14.0"
nalgebra = "0.33.2"
